# Generated by Django 3.2.4 on 2021-08-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_facturadet_facturaenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de supervisor de caja detalle')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('sup_caja_facturaenc', 'Permisos de supervisor de caja')], 'verbose_name': 'Encabezado Factura', 'verbose_name_plural': 'Encabezado Facturas'},
        ),
    ]
